#!/usr/bin/env python3
"""
🔧 First-Run Setup Wizard — Configure your DeepSeek API key.

Run this once before using the app:
    python setup.py

This creates a .secrets file with your API key so the AI interface can connect.
"""

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
SECRETS_PATH = PROJECT_ROOT / ".secrets"


def clear_screen():
    """Clear the terminal for a clean setup experience."""
    os.system("cls" if os.name == "nt" else "clear")


def print_header():
    """Print the setup wizard header."""
    clear_screen()
    print("=" * 60)
    print("  🧠  Ed's AI Interface — Setup Wizard")
    print("=" * 60)
    print()
    print("  This wizard will help you configure your DeepSeek API key.")
    print("  You'll need an API key from: https://platform.deepseek.com/api_keys")
    print()
    print("=" * 60)
    print()


def get_api_key() -> str:
    """Prompt the user for their DeepSeek API key."""
    print("📌 Step 1: Enter your DeepSeek API key")
    print()
    print("   Get your key at: https://platform.deepseek.com/api_keys")
    print("   It should look like: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    print()
    while True:
        key = input("   API Key: ").strip()
        if not key:
            print("   ❌ API key cannot be empty. Please try again.\n")
            continue
        if not key.startswith("sk-"):
            print("   ⚠️  That doesn't look like a DeepSeek key (should start with 'sk-').")
            confirm = input("   Use this key anyway? (y/n): ").strip().lower()
            if confirm != "y":
                continue
        return key


def select_model() -> str:
    """Let the user pick their preferred default model."""
    print()
    print("📌 Step 2: Choose your default model")
    print()
    models = {
        "1": ("deepseek-chat",        "DeepSeek V3 — fast, general-purpose (recommended)"),
        "2": ("deepseek-reasoner",    "DeepSeek R1 — advanced reasoning, slower"),
        "3": ("deepseek-coder",       "DeepSeek Coder — optimized for programming"),
    }
    for num, (name, desc) in models.items():
        print(f"   [{num}] {name}")
        print(f"       {desc}")
        print()
    while True:
        choice = input("   Choose [1-3] (default: 1): ").strip() or "1"
        if choice in models:
            return models[choice][0]
        print("   ❌ Invalid choice. Please enter 1, 2, or 3.\n")


def select_models_list() -> str:
    """Let the user configure which models appear in the menu."""
    print()
    print("📌 Step 3: Models to show in the selector menu")
    print()
    print("   These models will appear in the app's Model selector dropdown.")
    print("   Separate multiple models with commas.")
    print()
    default = "deepseek-chat, deepseek-reasoner, deepseek-coder"
    print(f"   Default: {default}")
    print()
    custom = input("   Models: ").strip()
    return custom if custom else default


def set_agent_name() -> str:
    """Let the user name their agent."""
    print()
    print("📌 Step 4: Name your AI assistant (optional)")
    print()
    name = input("   Agent name (default: Ed's AI Assistant): ").strip()
    return name if name else "Ed's AI Assistant"


def write_secrets(api_key: str, model: str, models_list: str, agent_name: str):
    """Write the .secrets file."""
    print()
    print("=" * 60)
    print("  💾 Saving configuration...")
    print("=" * 60)
    print()

    # Check if .secrets already exists
    if SECRETS_PATH.exists():
        print("   ⚠️  An existing .secrets file was found.")
        backup = input("   Overwrite it? (y/n): ").strip().lower()
        if backup != "y":
            print("   ❌ Setup cancelled. Your existing .secrets file was preserved.")
            sys.exit(0)

    content = f"""# =============================================================================
# 🔒 SECRETS — Your private API keys and configuration
# =============================================================================
# This file is gitignored — your keys stay safe.
# Generated by setup.py on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
#
# To change settings later, edit this file directly or re-run: python setup.py

# === DeepSeek API (required) ===
DEEPSEEK_API_KEY={api_key}
DEEPSEEK_MODEL={model}
DEEPSEEK_MODELS={models_list}

# === Agent Configuration ===
AGENT_NAME={agent_name}
AGENT_TEMPERATURE=0.7
AGENT_MAX_TOKENS=4096
AGENT_SYSTEM_PROMPT=You are a helpful AI assistant. You are knowledgeable, friendly, and context-aware. Use the conversation history and stored memories to provide personalized, relevant responses.
"""

    SECRETS_PATH.write_text(content, encoding="utf-8")

    print("   ✅ Configuration saved to .secrets")
    print()
    print("=" * 60)
    print("  🎉 Setup complete! You're ready to go.")
    print("=" * 60)
    print()
    print("   To launch the desktop app:")
    print("       python gui_main.py")
    print()
    print("   To launch the CLI version:")
    print("       python main.py")
    print()


def main():
    """Run the interactive setup wizard."""
    print_header()

    api_key = get_api_key()
    model = select_model()
    models_list = select_models_list()
    agent_name = set_agent_name()

    write_secrets(api_key, model, models_list, agent_name)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n   ❌ Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n\n   ❌ An error occurred: {e}")
        sys.exit(1)
